import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    nav: {
      home: 'Home',
      projects: 'Projects',
      certificates: 'Certificates',
      skills: 'Skills',
      about: 'About',
      contact: 'Contact'
    },
    home: {
      title: 'Ali Hassan',
      subtitle: 'Aspiring IT Systems Integration Specialist',
      description: 'Ready for Ausbildung with passion for technology and continuous learning',
      viewProjects: 'View My Projects',
      downloadCV: 'Download CV',
      achievements: 'My Achievements',
      professionalCertificates: 'Professional Certificates',
      completedProjects: 'Completed Projects',
      programmingLanguages: 'Programming Languages',
      commitmentToLearning: 'Commitment to Learning',
      whyRightChoice: 'Why I am the right choice',
      structuredLearning: 'Structured Learning',
      structuredLearningDesc: 'Ready to combine theoretical knowledge with practical experience through Ausbildung',
      careerFocus: 'Career Focus',
      careerFocusDesc: 'Committed to building a long-term career in IT and system integration',
      provenDedication: 'Proven Dedication',
      provenDedicationDesc: 'Self-motivated learner with completed certifications and real projects',
      readyNextStep: 'Ready for the next step',
      readyNextStepDesc: 'I look forward to deepening my passion for technology in structured training and gaining practical experience.',
      getInTouch: 'Get in Touch'
    },
    projects: {
      title: 'My Projects',
      subtitle: 'My implemented solutions – demonstrating the power of EAS in real-world applications',
      description: 'These projects were undertaken voluntarily, providing me the invaluable opportunity to launch my software and apply it in real-world scenarios.',
      allProjects: 'All Projects',
      webDevelopment: 'Web Development',
      artificialIntelligence: 'Artificial Intelligence',
      automation: 'Automation',
      systemIntegration: 'System Integration',
      hotelDigitalization: 'Hotel am Kochbrunnen Digitalization (AI Hospitality Suite)',
      hotelDigitalizationDesc: 'Complete digital transformation for Hotel am Kochbrunnen utilizing 8 integrated AI pillars. This includes PMS & Channel Manager migration, REST APIs for booking & payment, self-check-in kiosk, and a housekeeping bot. This project was a voluntary collaboration, allowing me to successfully launch and deploy my software in a live hospitality environment.',
      hotelResults: '40 hours monthly time saved, 99.9% system availability',
      hotelDetails: 'Explore how an 8-pillar AI strategy revolutionized hotel operations, from seamless booking to intelligent guest services and staff automation, achieving significant time savings and system stability.',
      
      falchiDental: 'Falchi Dental Tech Automation (Digital Dental Workflows)',
      falchiDentalDesc: 'Automation of dental lab processes with CAD/CAM integration, 3D scanner workflows, and network modernization. This voluntary project gave me the chance to put my software into practical use, significantly improving treatment accuracy and patient satisfaction, reducing diagnostic time by 40%.',
      falchiResults: '40% reduction in diagnostic time, improved treatment accuracy',
      falchiDetails: 'Discover the impact of automating dental lab processes, including CAD/CAM integration and optimized data transfer, leading to enhanced precision and operational efficiency.',
      
      glennMiller: 'Glenn Miller Piano School Website (AI-Enhanced Music Education Platform)',
      glennMillerDesc: 'Complete digital transformation with an intelligent booking system, student management, and AI-powered scheduling. Features AI Chatbots and an Analytics Dashboard. As a voluntary initiative, this project allowed for the live implementation of my software, resulting in a 50% increase in efficiency and 60% cost savings compared to competitors.',
      glennMillerResults: '50% increase in efficiency, 60% cost savings compared to competitors',
      glennMillerDetails: 'Learn about the AI-enhanced web platform for a piano school, featuring automated scheduling, payment integration, and smart chatbots for a more efficient and engaging learning experience.',
      
      eaSolutions: 'EA Solutions - AI & IT Services (Company Website)',
      eaSolutionsDesc: 'Professional company website for AI and IT services with modern design and service portfolio, powered by AI-driven development.',
      eaSolutionsDetails: 'Dive into the technical architecture and design principles behind a cutting-edge company website for AI and IT services, built with modern frontend frameworks and AI-driven functionalities.',
      
      eaAssistant: 'EA Local AI Assistant (Local AI Core & Home Assistant Module)',
      eaAssistantDesc: 'Development of a scalable, locally hosted AI system ("EA") as a privacy-friendly core for businesses and institutions. Based on STT/TTS pipelines, Wyoming Protocol, RAG, and locally hosted LLMs, focusing on multimodal processing (NLP + Computer Vision) and integration with external services.',
      eaAssistantDetails: 'Understand the development of a secure, local AI assistant with biometric speech recognition, multimodal processing, and extensive integration capabilities for business automation and smart home environments.',
      
      aiWebsite: 'AI-Generated Hotel Website',
      aiWebsiteDesc: 'Demonstration of AI-powered website generation with LLM Prompt-to-HTML conversion and focus on responsive design.',
      aiWebsiteDetails: 'See how large language models can be used to generate responsive web designs directly from prompts, showcasing the potential of AI in web development.',
      
      unitConverter: 'Unit Converter Web App',
      unitConverterDesc: 'IBM Full-Stack Capstone project with comprehensive unit conversion and modern UI.',
      unitConverterDetails: 'Get insights into the development of a robust unit conversion web application, built as a full-stack project with a focus on comprehensive functionality and user interface design.',
      
      languageApp: 'AI-Powered Language Learning App (Upcoming)',
      languageAppDesc: 'Currently under development, this innovative mobile and web application utilizes the I+1 teaching method to deliver a wide-ranging curriculum from A1.1 to C2 levels. It covers academic, professional, and general language topics, offering over 960 interactive lessons and 1.9 million words. Designed with a highly interactive UI/UX, it aims to revolutionize personalized language acquisition for smart learners.',
      languageAppFeatures: 'I+1 Method, AI-Generated Curriculum (A1.1-C2), 960+ Lessons, 1.9M+ Words, Interactive UI/UX',
      languageAppDetails: 'Discover the vision behind a revolutionary AI-powered language learning app designed for smart learners, featuring an extensive curriculum, adaptive learning methods, and a highly interactive user experience.',
      
      moreDetails: 'More Details',
      viewCode: 'View Code',
      liveDemo: 'Live Demo',
      visitWebsite: 'Visit Website',
      learnedSkills: 'Learned Skills',
      challenges: 'Challenges',
      technologiesUsed: 'Technologies Used',
      resultsAchievements: 'Results & Achievements',
      projectStatus: 'Project Status',
      completed: 'Completed',
      inDevelopment: 'In Development',
      more: 'more',
      code: 'Code',
      demo: 'Demo',
      website: 'Website',
      details: 'Details',
      close: 'Close',
      keyFeatures: 'Key Features',
      status: 'Status',
      results: 'Results',
      technologies: 'Technologies',
      learnings: 'Learnings',
      challengesOvercome: 'Challenges Overcome'
    },
    certificates: {
      title: 'Certifications',
      subtitle: 'Professional certifications and continuous learning achievements in AI, web development and technical support',
      certificatesReceived: 'Certificates Received',
      topProviders: 'Top Providers',
      verificationRate: 'Verification Rate',
      newSkills: 'New Skills',
      myAchievements: 'My Achievements',
      selfAcquiredKnowledge: 'Self-acquired knowledge and practical experience',
      verifyCertificate: 'Verify Certificate',
      continuousEducation: 'Continuous Education',
      continuousEducationDesc: 'These certifications reflect my commitment to continuous learning and professional development. Each certificate represents not only acquired knowledge, but also the willingness to face new challenges and keep up with the latest technologies.',
      goalOriented: 'Goal-oriented',
      goalOrientedDesc: 'Strategic selection of courses to deepen relevant IT skills',
      verified: 'Verified',
      verifiedDesc: 'All certificates are verifiable by renowned providers',
      futureOriented: 'Future-oriented',
      futureOrientedDesc: 'Focus on modern technologies and future-relevant skills',
      issuer: 'Issuer',
      date: 'Date',
      skills: 'Skills',
      viewCertificate: 'View Certificate',
      certificateDetails: 'Certificate Details'
    },
    skills: {
      title: 'My Skills',
      subtitle: 'Technical expertise through self-study and practical projects in modern web technologies, AI/ML tools and automation platforms',
      competencyAreas: 'Competency Areas',
      frontendDevelopment: 'Frontend Development',
      frontendDesc: 'Modern web development with responsive design and user-friendliness',
      backendDatabases: 'Backend & Databases',
      backendDesc: 'Server-side development and database management',
      devopsCloud: 'DevOps & Cloud',
      devopsDesc: 'Containerization, version control and deployment strategies',
      systemIntegration: 'System Integration',
      systemIntegrationDesc: 'Integration of complex systems and network administration',
      myLearningApproach: 'My Learning Approach',
      structuredLearning: 'Structured Learning',
      structuredLearningDesc: 'Systematic acquisition of new technologies through online courses and certifications',
      practicalApplication: 'Practical Application',
      practicalApplicationDesc: 'Implementation of what has been learned in real projects to deepen knowledge',
      continuousImprovement: 'Continuous Improvement',
      continuousImprovementDesc: 'Constant development and adaptation to new technologies and trends',
      advanced: 'Advanced',
      intermediate: 'Intermediate',
      beginner: 'Beginner',
      skillLevel: 'Skill Level',
      category: 'Category',
      frontend: 'Frontend',
      backend: 'Backend',
      database: 'Database',
      devops: 'DevOps',
      ai: 'AI/ML',
      infrastructure: 'Infrastructure'
    },
    about: {
      title: 'About Me',
      subtitle: 'Passionate technology enthusiast looking for training as a computer scientist',
      myMotivation: 'My Motivation',
      myBackground: 'My Background',
      myGoals: 'My Goals',
      languages: 'Languages',
      location: 'Location',
      locationDesc: 'Ready for training nationwide',
      interests: 'Interests',
      artificialIntelligence: 'Artificial Intelligence',
      systemIntegration: 'System Integration',
      networkTechnology: 'Network Technology',
      automation: 'Automation',
      myJourney: 'My Journey',
      plannedTraining: 'Planned Training',
      plannedTrainingSubtitle: 'IT Systems Integration Specialist',
      plannedTrainingDesc: 'Looking for a training position for a well-founded IT training with focus on system integration and network technology.',
      selfStudyCertifications: 'Self-study & Certifications',
      selfStudyCertificationsSubtitle: 'IBM & Google Courses',
      selfStudyCertificationsDesc: 'Intensive further education in AI, web development and technical support through internationally recognized online courses.',
      practicalProjects: 'Practical Projects',
      practicalProjectsSubtitle: 'Independent Development',
      practicalProjectsDesc: 'Development of various IT projects to deepen programming knowledge and system integration.',
      planned: 'Planned',
      completed: 'Completed',
      quote: 'Lifelong learning is the key to success in technology. Every project is a new opportunity to grow.',
      nativeLanguage: 'Native language',
      fluent: 'Fluent',
      advanced: 'Advanced',
      personalInfo: 'Personal Information',
      age: 'Age',
      years: 'years',
      availability: 'Availability',
      immediately: 'Immediately available',
      mobility: 'Mobility',
      nationwide: 'Nationwide',
      workPermit: 'Work Permit',
      euCitizen: 'EU Citizen'
    },
    contact: {
      title: 'Contact for Training Position',
      subtitle: 'Interested in a motivated trainee? Let\'s talk about training as an IT systems integration specialist.',
      whyRightCandidate: 'Why I am the right candidate',
      whyRightCandidateDesc: 'As a motivated and eager-to-learn candidate, I already bring practical experience in IT and am ready to deepen this in structured training. My independently acquired knowledge in programming, system integration and AI technologies shows my passion for technology and my ability to learn independently.',
      availabilityFlexibility: 'Availability & Flexibility',
      availability: 'Availability',
      availabilityDesc: 'Immediately available for training start',
      mobility: 'Mobility',
      mobilityDesc: 'Ready to relocate anywhere in Germany',
      documents: 'Documents',
      documentsDesc: 'Complete application documents available',
      contactInformation: 'Contact Information',
      onlineProfiles: 'Online Profiles',
      applicationDocuments: 'Application Documents',
      applicationDocumentsDesc: 'Download my complete CV or contact me for additional documents.',
      downloadCV: 'Download CV',
      interestedInConversation: 'Interested in a conversation?',
      yourName: 'Your Name',
      emailAddress: 'Email Address',
      company: 'Company',
      yourCompany: 'Your Company',
      position: 'Position',
      positionPlaceholder: 'Training supervisor, HR, etc.',
      message: 'Message',
      messagePlaceholder: 'Tell me about your training position and what you expect from a trainee...',
      sendMessage: 'Send Message',
      sending: 'Sending...',
      thankYou: 'Thank you for your interest! I will get back to you as soon as possible.',
      lookingForward: 'I look forward to your message and the opportunity to introduce myself personally.',
      nameRequired: 'Name is required',
      emailRequired: 'Email is required',
      invalidEmail: 'Invalid email address',
      messageRequired: 'Message is required',
      quickContact: 'Quick Contact',
      phone: 'Phone',
      email: 'Email',
      call: 'Call',
      location: 'Location',
      wiesbaden: 'Wiesbaden, Germany'
    },
    cv: {
      download: 'Download CV',
      downloading: 'Downloading...',
      downloaded: 'Downloaded!',
      error: 'Download Error',
      downloadAria: 'Download CV as PDF',
      resume: 'Resume',
      curriculum: 'Curriculum Vitae'
    },
    footer: {
      quickLinks: 'Quick Links',
      connect: 'Connect',
      allRightsReserved: 'All rights reserved',
      madeWith: 'Made with',
      and: 'and',
      portfolio: 'Portfolio',
      socialMedia: 'Social Media',
      github: 'GitHub',
      linkedin: 'LinkedIn',
      email: 'Email'
    },
    chat: {
      greeting: 'Hello! I am Ali\'s portfolio assistant. Do you have questions about my training readiness or my projects?',
      placeholder: 'Questions about training...',
      demoMode: 'Demo mode: Simulated responses',
      portfolioAssistant: 'Portfolio Assistant',
      trainingCareer: 'Training & Career',
      send: 'Send',
      close: 'Close',
      user: 'User',
      assistant: 'Assistant'
    },
    cli: {
      welcome: 'Ali Hassan Portfolio Terminal v1.0 - Training Edition',
      helpPrompt: 'Type "help" for available commands.',
      availableCommands: 'Available commands:',
      help: 'Show this help',
      aboutAli: 'About Ali Hassan',
      trainingGoals: 'Training goals and readiness',
      listSkills: 'List technical skills',
      showProjects: 'Show project list',
      contactInfo: 'Contact information',
      motivationForTraining: 'Motivation for training',
      clearTerminal: 'Clear terminal',
      closeTerminal: 'Close terminal',
      terminalCleared: 'Terminal cleared.',
      commandNotFound: 'Command not found',
      helpForCommands: 'Type "help" for available commands.',
      tipMessage: 'Tip: Press ~ to open terminal, "help" for commands',
      terminal: 'Terminal',
      command: 'Command',
      output: 'Output'
    },
    common: {
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      cancel: 'Cancel',
      confirm: 'Confirm',
      save: 'Save',
      edit: 'Edit',
      delete: 'Delete',
      view: 'View',
      back: 'Back',
      next: 'Next',
      previous: 'Previous',
      search: 'Search',
      filter: 'Filter',
      sort: 'Sort',
      clear: 'Clear',
      reset: 'Reset',
      submit: 'Submit',
      apply: 'Apply',
      close: 'Close',
      open: 'Open',
      show: 'Show',
      hide: 'Hide',
      expand: 'Expand',
      collapse: 'Collapse',
      select: 'Select',
      deselect: 'Deselect',
      all: 'All',
      none: 'None',
      yes: 'Yes',
      no: 'No',
      ok: 'OK',
      done: 'Done',
      continue: 'Continue',
      skip: 'Skip',
      retry: 'Retry',
      refresh: 'Refresh',
      update: 'Update',
      upgrade: 'Upgrade',
      download: 'Download',
      upload: 'Upload',
      import: 'Import',
      export: 'Export',
      print: 'Print',
      share: 'Share',
      copy: 'Copy',
      paste: 'Paste',
      cut: 'Cut',
      undo: 'Undo',
      redo: 'Redo'
    }
  },
  de: {
    nav: {
      home: 'Startseite',
      projects: 'Projekte',
      certificates: 'Zertifikate',
      skills: 'Fähigkeiten',
      about: 'Über mich',
      contact: 'Kontakt'
    },
    home: {
      title: 'Ali Hassan',
      subtitle: 'Angehender Fachinformatiker für Systemintegration',
      description: 'Bereit für eine Ausbildung mit Leidenschaft für Technologie und kontinuierliches Lernen',
      viewProjects: 'Meine Projekte ansehen',
      downloadCV: 'Lebenslauf herunterladen',
      achievements: 'Meine Erfolge',
      professionalCertificates: 'Professionelle Zertifikate',
      completedProjects: 'Abgeschlossene Projekte',
      programmingLanguages: 'Programmiersprachen',
      commitmentToLearning: 'Engagement für das Lernen',
      whyRightChoice: 'Warum ich die richtige Wahl bin',
      structuredLearning: 'Strukturiertes Lernen',
      structuredLearningDesc: 'Bereit, theoretisches Wissen mit praktischer Erfahrung durch Ausbildung zu kombinieren',
      careerFocus: 'Karrierefokus',
      careerFocusDesc: 'Engagiert für den Aufbau einer langfristigen Karriere in der IT und Systemintegration',
      provenDedication: 'Bewiesene Hingabe',
      provenDedicationDesc: 'Selbstmotivierter Lerner mit abgeschlossenen Zertifizierungen und echten Projekten',
      readyNextStep: 'Bereit für den nächsten Schritt',
      readyNextStepDesc: 'Ich freue mich darauf, meine Leidenschaft für Technologie in einer strukturierten Ausbildung zu vertiefen und praktische Erfahrungen zu sammeln.',
      getInTouch: 'Kontakt aufnehmen'
    },
    projects: {
      title: 'Meine Projekte',
      subtitle: 'Meine implementierten Lösungen – demonstrieren die Kraft von EAS in realen Anwendungen',
      description: 'Diese Projekte wurden freiwillig durchgeführt und boten mir die unschätzbare Gelegenheit, meine Software zu starten und in realen Szenarien anzuwenden.',
      allProjects: 'Alle Projekte',
      webDevelopment: 'Webentwicklung',
      artificialIntelligence: 'Künstliche Intelligenz',
      automation: 'Automatisierung',
      systemIntegration: 'Systemintegration',
      hotelDigitalization: 'Hotel am Kochbrunnen Digitalisierung (AI Hospitality Suite)',
      hotelDigitalizationDesc: 'Komplette digitale Transformation für Hotel am Kochbrunnen mit 8 integrierten KI-Säulen. Dazu gehören PMS & Channel Manager Migration, REST APIs für Buchung & Zahlung, Self-Check-in Kiosk und ein Housekeeping-Bot. Dieses Projekt war eine freiwillige Zusammenarbeit, die es mir ermöglichte, meine Software erfolgreich in einer Live-Hospitality-Umgebung zu starten und einzusetzen.',
      hotelResults: '40 Stunden monatliche Zeitersparnis, 99,9% Systemverfügbarkeit',
      hotelDetails: 'Entdecken Sie, wie eine 8-Säulen-KI-Strategie den Hotelbetrieb revolutionierte, von nahtlosen Buchungen bis hin zu intelligenten Gästeservices und Personalautomatisierung, mit erheblichen Zeiteinsparungen und Systemstabilität.',
      
      falchiDental: 'Falchi Dental Tech Automatisierung (Digitale Dental-Workflows)',
      falchiDentalDesc: 'Automatisierung von Dentallabor-Prozessen mit CAD/CAM-Integration, 3D-Scanner-Workflows und Netzwerkmodernisierung. Dieses freiwillige Projekt gab mir die Chance, meine Software praktisch einzusetzen, wodurch die Behandlungsgenauigkeit und Patientenzufriedenheit erheblich verbessert und die Diagnosezeit um 40% reduziert wurde.',
      falchiResults: '40% Reduzierung der Diagnosezeit, verbesserte Behandlungsgenauigkeit',
      falchiDetails: 'Entdecken Sie die Auswirkungen der Automatisierung von Dentallabor-Prozessen, einschließlich CAD/CAM-Integration und optimiertem Datentransfer, was zu erhöhter Präzision und betrieblicher Effizienz führt.',
      
      glennMiller: 'Glenn Miller Klavierschule Website (KI-erweiterte Musikbildungsplattform)',
      glennMillerDesc: 'Komplette digitale Transformation mit intelligentem Buchungssystem, Schülerverwaltung und KI-gestützter Terminplanung. Mit KI-Chatbots und Analytics Dashboard. Als freiwillige Initiative ermöglichte dieses Projekt die Live-Implementierung meiner Software, was zu 50% Effizienzsteigerung und 60% Kosteneinsparung gegenüber Konkurrenten führte.',
      glennMillerResults: '50% Effizienzsteigerung, 60% Kosteneinsparung gegenüber Konkurrenten',
      glennMillerDetails: 'Erfahren Sie mehr über die KI-erweiterte Webplattform für eine Klavierschule mit automatisierter Terminplanung, Zahlungsintegration und intelligenten Chatbots für ein effizienteres und ansprechenderes Lernerlebnis.',
      
      eaSolutions: 'EA Solutions - KI & IT Services (Unternehmenswebsite)',
      eaSolutionsDesc: 'Professionelle Unternehmenswebsite für KI- und IT-Services mit modernem Design und Service-Portfolio, angetrieben von KI-gestützter Entwicklung.',
      eaSolutionsDetails: 'Tauchen Sie ein in die technische Architektur und Designprinzipien hinter einer hochmodernen Unternehmenswebsite für KI- und IT-Services, gebaut mit modernen Frontend-Frameworks und KI-gestützten Funktionalitäten.',
      
      eaAssistant: 'EA Local AI Assistant (Lokaler KI-Kern & Home Assistant Modul)',
      eaAssistantDesc: 'Entwicklung eines skalierbaren, lokal gehosteten KI-Systems ("EA") als datenschutzfreundlicher Kern für Unternehmen und Institutionen. Basierend auf STT/TTS-Pipelines, Wyoming Protocol, RAG und lokal gehosteten LLMs, mit Fokus auf multimodale Verarbeitung (NLP + Computer Vision) und Integration mit externen Services.',
      eaAssistantDetails: 'Verstehen Sie die Entwicklung eines sicheren, lokalen KI-Assistenten mit biometrischer Spracherkennung, multimodaler Verarbeitung und umfangreichen Integrationsmöglichkeiten für Unternehmensautomatisierung und Smart-Home-Umgebungen.',
      
      aiWebsite: 'KI-generierte Hotel-Website',
      aiWebsiteDesc: 'Demonstration von KI-gestützter Website-Generierung mit LLM Prompt-zu-HTML-Konvertierung und Fokus auf responsives Design.',
      aiWebsiteDetails: 'Sehen Sie, wie große Sprachmodelle verwendet werden können, um responsive Webdesigns direkt aus Prompts zu generieren und das Potenzial von KI in der Webentwicklung zu zeigen.',
      
      unitConverter: 'Unit Converter Web App',
      unitConverterDesc: 'IBM Full-Stack Capstone-Projekt mit umfassender Einheitenkonvertierung und moderner Benutzeroberfläche.',
      unitConverterDetails: 'Erhalten Sie Einblicke in die Entwicklung einer robusten Einheitenkonvertierungs-Webanwendung, gebaut als Full-Stack-Projekt mit Fokus auf umfassende Funktionalität und Benutzeroberflächendesign.',
      
      languageApp: 'KI-gestützte Sprachlern-App (In Entwicklung)',
      languageAppDesc: 'Derzeit in Entwicklung befindliche innovative mobile und Web-Anwendung, die die I+1-Lehrmethode nutzt, um ein umfassendes Curriculum von A1.1 bis C2-Level zu liefern. Sie deckt akademische, berufliche und allgemeine Sprachthemen ab und bietet über 960 interaktive Lektionen und 1,9 Millionen Wörter. Mit hochinteraktiver UI/UX entwickelt, zielt sie darauf ab, den personalisierten Spracherwerb für intelligente Lerner zu revolutionieren.',
      languageAppFeatures: 'I+1-Methode, KI-generiertes Curriculum (A1.1-C2), 960+ Lektionen, 1,9M+ Wörter, Interaktive UI/UX',
      languageAppDetails: 'Entdecken Sie die Vision hinter einer revolutionären KI-gestützten Sprachlern-App für intelligente Lerner mit umfangreichem Curriculum, adaptiven Lernmethoden und hochinteraktiver Benutzererfahrung.',
      
      moreDetails: 'Weitere Details',
      viewCode: 'Code ansehen',
      liveDemo: 'Live Demo',
      visitWebsite: 'Website besuchen',
      learnedSkills: 'Gelernte Fähigkeiten',
      challenges: 'Herausforderungen',
      technologiesUsed: 'Verwendete Technologien',
      resultsAchievements: 'Ergebnisse & Erfolge',
      projectStatus: 'Projektstatus',
      completed: 'Abgeschlossen',
      inDevelopment: 'In Entwicklung',
      more: 'weitere',
      code: 'Code',
      demo: 'Demo',
      website: 'Website',
      details: 'Details',
      close: 'Schließen',
      keyFeatures: 'Hauptmerkmale',
      status: 'Status',
      results: 'Ergebnisse',
      technologies: 'Technologien',
      learnings: 'Erkenntnisse',
      challengesOvercome: 'Überwundene Herausforderungen'
    },
    certificates: {
      title: 'Zertifizierungen',
      subtitle: 'Professionelle Zertifizierungen und kontinuierliche Lernerfolge in KI, Webentwicklung und technischem Support',
      certificatesReceived: 'Erhaltene Zertifikate',
      topProviders: 'Top-Anbieter',
      verificationRate: 'Verifizierungsrate',
      newSkills: 'Neue Fähigkeiten',
      myAchievements: 'Meine Erfolge',
      selfAcquiredKnowledge: 'Selbstständig erworbene Kenntnisse und praktische Erfahrungen',
      verifyCertificate: 'Zertifikat verifizieren',
      continuousEducation: 'Kontinuierliche Weiterbildung',
      continuousEducationDesc: 'Diese Zertifizierungen spiegeln mein Engagement für kontinuierliches Lernen und professionelle Entwicklung wider. Jedes Zertifikat repräsentiert nicht nur erworbenes Wissen, sondern auch die Bereitschaft, sich neuen Herausforderungen zu stellen und mit den neuesten Technologien Schritt zu halten.',
      goalOriented: 'Zielorientiert',
      goalOrientedDesc: 'Strategische Auswahl von Kursen zur Vertiefung relevanter IT-Kompetenzen',
      verified: 'Verifiziert',
      verifiedDesc: 'Alle Zertifikate sind durch renommierte Anbieter verifizierbar',
      futureOriented: 'Zukunftsorientiert',
      futureOrientedDesc: 'Fokus auf moderne Technologien und zukunftsrelevante Fähigkeiten',
      issuer: 'Aussteller',
      date: 'Datum',
      skills: 'Fähigkeiten',
      viewCertificate: 'Zertifikat ansehen',
      certificateDetails: 'Zertifikatsdetails'
    },
    skills: {
      title: 'Meine Fähigkeiten',
      subtitle: 'Technische Expertise durch Selbststudium und praktische Projekte in modernen Webtechnologien, KI/ML-Tools und Automatisierungsplattformen',
      competencyAreas: 'Kompetenzbereiche',
      frontendDevelopment: 'Frontend-Entwicklung',
      frontendDesc: 'Moderne Webentwicklung mit responsivem Design und Benutzerfreundlichkeit',
      backendDatabases: 'Backend & Datenbanken',
      backendDesc: 'Server-seitige Entwicklung und Datenbankmanagement',
      devopsCloud: 'DevOps & Cloud',
      devopsDesc: 'Containerisierung, Versionskontrolle und Deployment-Strategien',
      systemIntegration: 'Systemintegration',
      systemIntegrationDesc: 'Integration komplexer Systeme und Netzwerkadministration',
      myLearningApproach: 'Mein Lernansatz',
      structuredLearning: 'Strukturiertes Lernen',
      structuredLearningDesc: 'Systematische Aneignung neuer Technologien durch Online-Kurse und Zertifizierungen',
      practicalApplication: 'Praktische Anwendung',
      practicalApplicationDesc: 'Umsetzung des Gelernten in realen Projekten zur Vertiefung der Kenntnisse',
      continuousImprovement: 'Kontinuierliche Verbesserung',
      continuousImprovementDesc: 'Ständige Weiterentwicklung und Anpassung an neue Technologien und Trends',
      advanced: 'Fortgeschritten',
      intermediate: 'Mittelstufe',
      beginner: 'Grundlagen',
      skillLevel: 'Fähigkeitslevel',
      category: 'Kategorie',
      frontend: 'Frontend',
      backend: 'Backend',
      database: 'Datenbank',
      devops: 'DevOps',
      ai: 'KI/ML',
      infrastructure: 'Infrastruktur'
    },
    about: {
      title: 'Über mich',
      subtitle: 'Leidenschaftlicher Technologie-Enthusiast auf der Suche nach einer Ausbildung zum Fachinformatiker',
      myMotivation: 'Meine Motivation',
      myBackground: 'Mein Hintergrund',
      myGoals: 'Meine Ziele',
      languages: 'Sprachen',
      location: 'Standort',
      locationDesc: 'Bereit für Ausbildung deutschlandweit',
      interests: 'Interessen',
      artificialIntelligence: 'Künstliche Intelligenz',
      systemIntegration: 'Systemintegration',
      networkTechnology: 'Netzwerktechnik',
      automation: 'Automatisierung',
      myJourney: 'Mein Werdegang',
      plannedTraining: 'Geplante Ausbildung',
      plannedTrainingSubtitle: 'Fachinformatiker für Systemintegration',
      plannedTrainingDesc: 'Suche nach einem Ausbildungsplatz für eine fundierte IT-Ausbildung mit Fokus auf Systemintegration und Netzwerktechnik.',
      selfStudyCertifications: 'Selbststudium & Zertifizierungen',
      selfStudyCertificationsSubtitle: 'IBM & Google Kurse',
      selfStudyCertificationsDesc: 'Intensive Weiterbildung in AI, Webentwicklung und technischem Support durch international anerkannte Online-Kurse.',
      practicalProjects: 'Praktische Projekte',
      practicalProjectsSubtitle: 'Eigenständige Entwicklung',
      practicalProjectsDesc: 'Entwicklung verschiedener IT-Projekte zur Vertiefung der Programmierkenntnisse und Systemintegration.',
      planned: 'Geplant',
      completed: 'Abgeschlossen',
      quote: 'Lebenslanges Lernen ist der Schlüssel zum Erfolg in der Technologie. Jedes Projekt ist eine neue Gelegenheit zu wachsen.',
      nativeLanguage: 'Muttersprache',
      fluent: 'Fließend',
      advanced: 'Fortgeschritten',
      personalInfo: 'Persönliche Informationen',
      age: 'Alter',
      years: 'Jahre',
      availability: 'Verfügbarkeit',
      immediately: 'Sofort verfügbar',
      mobility: 'Mobilität',
      nationwide: 'Deutschlandweit',
      workPermit: 'Arbeitserlaubnis',
      euCitizen: 'EU-Bürger'
    },
    contact: {
      title: 'Kontakt für Ausbildungsplatz',
      subtitle: 'Interessiert an einem motivierten Auszubildenden? Lassen Sie uns über eine Ausbildung zum Fachinformatiker für Systemintegration sprechen.',
      whyRightCandidate: 'Warum ich der richtige Kandidat bin',
      whyRightCandidateDesc: 'Als motivierter und lernbereiter Kandidat bringe ich bereits praktische Erfahrungen in der IT mit und bin bereit, diese in einer strukturierten Ausbildung zu vertiefen. Meine selbstständig erworbenen Kenntnisse in Programmierung, Systemintegration und KI-Technologien zeigen meine Leidenschaft für Technologie und meine Fähigkeit zum eigenständigen Lernen.',
      availabilityFlexibility: 'Verfügbarkeit & Flexibilität',
      availability: 'Verfügbarkeit',
      availabilityDesc: 'Sofort verfügbar für Ausbildungsbeginn',
      mobility: 'Mobilität',
      mobilityDesc: 'Bereit für Umzug deutschlandweit',
      documents: 'Dokumente',
      documentsDesc: 'Vollständige Bewerbungsunterlagen verfügbar',
      contactInformation: 'Kontaktinformationen',
      onlineProfiles: 'Online-Profile',
      applicationDocuments: 'Bewerbungsunterlagen',
      applicationDocumentsDesc: 'Laden Sie meinen vollständigen Lebenslauf herunter oder kontaktieren Sie mich für weitere Unterlagen.',
      downloadCV: 'Lebenslauf herunterladen',
      interestedInConversation: 'Interesse an einem Gespräch?',
      yourName: 'Ihr Name',
      emailAddress: 'E-Mail-Adresse',
      company: 'Unternehmen',
      yourCompany: 'Ihr Unternehmen',
      position: 'Position',
      positionPlaceholder: 'Ausbildungsleiter, HR, etc.',
      message: 'Nachricht',
      messagePlaceholder: 'Erzählen Sie mir von Ihrem Ausbildungsplatz und was Sie von einem Auszubildenden erwarten...',
      sendMessage: 'Nachricht senden',
      sending: 'Wird gesendet...',
      thankYou: 'Vielen Dank für Ihr Interesse! Ich melde mich schnellstmöglich bei Ihnen.',
      lookingForward: 'Ich freue mich auf Ihre Nachricht und die Möglichkeit, mich persönlich vorstellen zu können.',
      nameRequired: 'Name ist erforderlich',
      emailRequired: 'E-Mail ist erforderlich',
      invalidEmail: 'Ungültige E-Mail-Adresse',
      messageRequired: 'Nachricht ist erforderlich',
      quickContact: 'Schnellkontakt',
      phone: 'Telefon',
      email: 'E-Mail',
      call: 'Anrufen',
      location: 'Standort',
      wiesbaden: 'Wiesbaden, Deutschland'
    },
    cv: {
      download: 'Lebenslauf herunterladen',
      downloading: 'Wird heruntergeladen...',
      downloaded: 'Heruntergeladen!',
      error: 'Fehler beim Download',
      downloadAria: 'Lebenslauf als PDF herunterladen',
      resume: 'Lebenslauf',
      curriculum: 'Curriculum Vitae'
    },
    footer: {
      quickLinks: 'Schnellzugriff',
      connect: 'Verbinden',
      allRightsReserved: 'Alle Rechte vorbehalten',
      madeWith: 'Erstellt mit',
      and: 'und',
      portfolio: 'Portfolio',
      socialMedia: 'Soziale Medien',
      github: 'GitHub',
      linkedin: 'LinkedIn',
      email: 'E-Mail'
    },
    chat: {
      greeting: 'Hallo! Ich bin Ali\'s Portfolio-Assistent. Haben Sie Fragen zu meiner Ausbildungsbereitschaft oder meinen Projekten?',
      placeholder: 'Fragen zur Ausbildung...',
      demoMode: 'Demo-Modus: Simulierte Antworten',
      portfolioAssistant: 'Portfolio-Assistent',
      trainingCareer: 'Ausbildung & Karriere',
      send: 'Senden',
      close: 'Schließen',
      user: 'Benutzer',
      assistant: 'Assistent'
    },
    cli: {
      welcome: 'Ali Hassan Portfolio Terminal v1.0 - Ausbildung Edition',
      helpPrompt: 'Geben Sie "help" für verfügbare Befehle ein.',
      availableCommands: 'Verfügbare Befehle:',
      help: 'Diese Hilfe anzeigen',
      aboutAli: 'Über Ali Hassan',
      trainingGoals: 'Ausbildungsziele und -bereitschaft',
      listSkills: 'Technische Fähigkeiten auflisten',
      showProjects: 'Projektliste anzeigen',
      contactInfo: 'Kontaktinformationen',
      motivationForTraining: 'Motivation für Ausbildung',
      clearTerminal: 'Terminal leeren',
      closeTerminal: 'Terminal schließen',
      terminalCleared: 'Terminal geleert.',
      commandNotFound: 'Befehl nicht gefunden',
      helpForCommands: 'Geben Sie "help" für verfügbare Befehle ein.',
      tipMessage: 'Tipp: Drücken Sie ~ um das Terminal zu öffnen, "help" für Befehle',
      terminal: 'Terminal',
      command: 'Befehl',
      output: 'Ausgabe'
    },
    common: {
      loading: 'Lädt...',
      error: 'Fehler',
      success: 'Erfolg',
      cancel: 'Abbrechen',
      confirm: 'Bestätigen',
      save: 'Speichern',
      edit: 'Bearbeiten',
      delete: 'Löschen',
      view: 'Ansehen',
      back: 'Zurück',
      next: 'Weiter',
      previous: 'Vorherige',
      search: 'Suchen',
      filter: 'Filtern',
      sort: 'Sortieren',
      clear: 'Löschen',
      reset: 'Zurücksetzen',
      submit: 'Absenden',
      apply: 'Anwenden',
      close: 'Schließen',
      open: 'Öffnen',
      show: 'Anzeigen',
      hide: 'Verbergen',
      expand: 'Erweitern',
      collapse: 'Einklappen',
      select: 'Auswählen',
      deselect: 'Abwählen',
      all: 'Alle',
      none: 'Keine',
      yes: 'Ja',
      no: 'Nein',
      ok: 'OK',
      done: 'Fertig',
      continue: 'Fortfahren',
      skip: 'Überspringen',
      retry: 'Wiederholen',
      refresh: 'Aktualisieren',
      update: 'Aktualisieren',
      upgrade: 'Upgrade',
      download: 'Herunterladen',
      upload: 'Hochladen',
      import: 'Importieren',
      export: 'Exportieren',
      print: 'Drucken',
      share: 'Teilen',
      copy: 'Kopieren',
      paste: 'Einfügen',
      cut: 'Ausschneiden',
      undo: 'Rückgängig',
      redo: 'Wiederholen'
    }
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('de'); // Always load in German first

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};